version: "2"
services:
  web:
    build: .
    command: rails s -b "0.0.0.0"
    volumes:
      - .:/theapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:9.6
    ports:
      - "5432"
